### ISSUE TITLE
inotify: watcher thread panics when system is supended and resumed

### ISSUE THREAD

**Issue by fkrull** [notify-rs/notify#283]
#### System details

- OS/Platform name and version: Linux (at least 5.4.0-65-generic and 5.10.12-200.fc33.x86_64)
- Rust version (if building from source): `rustc --version`: 1.49.0
- Notify version (or commit hash if building from git): 5.0.0-pre.5

The notify-rs watcher thread panics after suspending and then resuming the system. At the very least, this breaks file watching so no events are reported any more. In my application, this even crashes it because I set it to quit on thread panic.

#### Panic
```shell
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/notify-panic`
[machine was suspended and resumed here]
thread '<unnamed>' panicked at 'poll failed: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/fk/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.5/src/inotify.rs:134:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::expect
             at /home/fk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933:23
   4: notify::inotify::EventLoop::event_loop_thread
             at /home/fk/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.5/src/inotify.rs:134:13
   5: notify::inotify::EventLoop::run::{{closure}}
             at /home/fk/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.5/src/inotify.rs:127:26
```

#### Repro
This was easily reproducible with a sample program:
```rust
use notify::{RecommendedWatcher, RecursiveMode, Watcher};

fn main() {
    let mut watcher: RecommendedWatcher = Watcher::new_immediate(|res| match res {
        Ok(event) => println!("event: {:?}", event),
        Err(e) => println!("watch error: {:?}", e),
    })
    .unwrap();

    watcher.watch(".", RecursiveMode::Recursive).unwrap();

    loop {
        std::thread::sleep(std::time::Duration::from_secs(3600));
    }
}
```

Steps:
* build with notify-rs 5.0.0-pre.5
* run
* suspend and then resume the system (for example, by closing the lid on a laptop)
* panic happens

**Comment by 0xpr03** [comment]
This shouldn't happen after #281 has landed.

**Comment by 0xpr03** [comment]
You can now also test this directly with the new 5.0.0-pre.6 release.

**Comment by fkrull** [comment]
Oh excellent! I didn't check the PRs for the issue. Glad to see it is already fixed.

**Comment by 0xpr03** [comment]
@fkrull could you try the new version and report if that worked ? so we can close this issue if this really fixed your problem

**Comment by fkrull** [comment]
Yup, the new pre.6 version fixed the problem! 👍

**Comment by 0xpr03** [comment]
Thanks for verifying!
